// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvx6wBnMPDw_HsJmn8zR-VngCAMbkW9HA',
    appId: '1:834136063081:web:a2fd1bb1a665369a2436f8',
    messagingSenderId: '834136063081',
    projectId: 'habit-tracker-30556',
    authDomain: 'habit-tracker-30556.firebaseapp.com',
    storageBucket: 'habit-tracker-30556.firebasestorage.app',
    measurementId: 'G-FTR2DG2EP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYKbNEfRKFTZwnU-m_r5toYbyO2wLK6L0',
    appId: '1:834136063081:android:82d30aef60bd49e02436f8',
    messagingSenderId: '834136063081',
    projectId: 'habit-tracker-30556',
    storageBucket: 'habit-tracker-30556.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgbYBQrLrYZ94_Q5OJfvfPJa-zrQPOQqE',
    appId: '1:834136063081:ios:f16e55961be8ed5f2436f8',
    messagingSenderId: '834136063081',
    projectId: 'habit-tracker-30556',
    storageBucket: 'habit-tracker-30556.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgbYBQrLrYZ94_Q5OJfvfPJa-zrQPOQqE',
    appId: '1:834136063081:ios:f16e55961be8ed5f2436f8',
    messagingSenderId: '834136063081',
    projectId: 'habit-tracker-30556',
    storageBucket: 'habit-tracker-30556.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvx6wBnMPDw_HsJmn8zR-VngCAMbkW9HA',
    appId: '1:834136063081:web:e5369243d13ec3592436f8',
    messagingSenderId: '834136063081',
    projectId: 'habit-tracker-30556',
    authDomain: 'habit-tracker-30556.firebaseapp.com',
    storageBucket: 'habit-tracker-30556.firebasestorage.app',
    measurementId: 'G-G9R5402LZN',
  );
}
